# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: circleci/python:3.6.1
      - image: docker:19.03

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build Docker Image and Push to DockerHub
          command: |
            TAG=$CIRCLE_BUILD_NUM
            IMAGE_NAME="yahmlevi/python"

            # build docker image
            docker build -t $IMAGE_NAME:$TAG .

            # tag with "latest"
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

            # login to DockerHub
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

            # push to DockerHub (both with build number and latest)
            docker push $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest

      - run:
          name: Build OpenCV Docker Image and Push to DockerHub
          command: |
            TAG=$CIRCLE_BUILD_NUM
            IMAGE_NAME="yahmlevi/opencv"

            # build docker image
            docker build -t $IMAGE_NAME:$TAG .

            # tag with "latest"
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

            # login to DockerHub
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

            # push to DockerHub (both with build number and latest)
            docker push $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest
