version: 2.1

orbs:
  # docker-buildx: foodles/docker-buildx@0.0.1
  # terraform: devops-workflow/terraform@0.0.1

jobs:
  build:
    docker:
      - image: docker:19.03

    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      
      - terraform/terraform_fmt
      
      # - docker-buildx/publish:
      #     dockerfile: ./docker/dockerfiles/opencv.dockerfile
      #     image: yahmlevi/opencv:$CIRCLE_BUILD_NUM

      # - run:
      #     name: Build 'Python' Docker Image and Push to DockerHub
      #     command: |
      #       TAG=$CIRCLE_BUILD_NUM
      #       IMAGE_NAME="yahmlevi/python"
      #       DOCKERFILE="./docker/dockerfiles/python.dockerfile"

      #       # build docker image
      #       docker build --tag $IMAGE_NAME:$TAG -f $DOCKERFILE .

      #       # tag with "latest"
      #       docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      #       # login to DockerHub
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      #       # push to DockerHub (both with build number and latest)
      #       docker push $IMAGE_NAME:$TAG
      #       docker push $IMAGE_NAME:latest

      # - run:
      #     name: Build 'OpenCV' Docker Image and Push to DockerHub
      #     command: |
      #       TAG=$CIRCLE_BUILD_NUM
      #       IMAGE_NAME="yahmlevi/opencv"
      #       DOCKERFILE="./docker/dockerfiles/opencv.dockerfile"

      #       # build docker image
      #       docker build -t $IMAGE_NAME:$TAG -f $DOCKERFILE .

      #       # tag with "latest"
      #       docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      #       # login to DockerHub
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      #       # push to DockerHub (both with build number and latest)
      #       docker push $IMAGE_NAME:$TAG
      #       docker push $IMAGE_NAME:latest
