version: 2.1

orbs:
#   # docker-buildx: foodles/docker-buildx@0.0.1
#   terraform: devops-workflow/terraform@0.0.1
  bt: circleci/build-tools@2.6.3
  orb-tools: circleci/orb-tools@8.8.0
  docker: circleci/docker@0.5.13

jobs:
  build:
    docker:
      - image: docker:19.03

    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      
      # - terraform/terraform_fmt
      - run:
          name: Remove old installation
          command: |
            sudo systemctl stop docker.service
            sudo apt remove docker-ce docker-ce-cli containerd.io

      - docker/install-docker:
          install-dir: /usr/bin

      - run:
          name: Restart docker daemon
          command: |
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
            $SUDO systemctl unmask docker.service
            $SUDO systemctl unmask docker.socket
            $SUDO systemctl start docker.service

      - run: 
          name: Test Docker
          command: |
            docker run hello-world
      
      # - docker-buildx/publish:
      #     dockerfile: ./docker/dockerfiles/opencv.dockerfile
      #     image: yahmlevi/opencv:$CIRCLE_BUILD_NUM

      # - run:
      #     name: Build 'Python' Docker Image and Push to DockerHub
      #     command: |
      #       TAG=$CIRCLE_BUILD_NUM
      #       IMAGE_NAME="yahmlevi/python"
      #       DOCKERFILE="./docker/dockerfiles/python.dockerfile"

      #       # build docker image
      #       docker build --tag $IMAGE_NAME:$TAG -f $DOCKERFILE .

      #       # tag with "latest"
      #       docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      #       # login to DockerHub
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      #       # push to DockerHub (both with build number and latest)
      #       docker push $IMAGE_NAME:$TAG
      #       docker push $IMAGE_NAME:latest

      # - run:
      #     name: Build 'OpenCV' Docker Image and Push to DockerHub
      #     command: |
      #       TAG=$CIRCLE_BUILD_NUM
      #       IMAGE_NAME="yahmlevi/opencv"
      #       DOCKERFILE="./docker/dockerfiles/opencv.dockerfile"

      #       # build docker image
      #       docker build -t $IMAGE_NAME:$TAG -f $DOCKERFILE .

      #       # tag with "latest"
      #       docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      #       # login to DockerHub
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      #       # push to DockerHub (both with build number and latest)
      #       docker push $IMAGE_NAME:$TAG
      #       docker push $IMAGE_NAME:latest
