version: 2
jobs:
  build:
    docker:
      - image: docker:19.03

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build 'Python' Docker Image and Push to DockerHub
          command: |
            TAG=$CIRCLE_BUILD_NUM
            IMAGE_NAME="yahmlevi/python"
            DOCKERFILE="./docker/python.dockerfile"

            # build docker image
            docker build --tag $IMAGE_NAME:$TAG -f $DOCKERFILE .

            # tag with "latest"
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

            # login to DockerHub
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

            # push to DockerHub (both with build number and latest)
            docker push $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest

      - run:
          name: Build 'OpenCV' Docker Image and Push to DockerHub
          command: |
            TAG=$CIRCLE_BUILD_NUM
            IMAGE_NAME="yahmlevi/opencv"
            DOCKERFILE="./docker/opencv.dockerfile"

            # build docker image
            docker build -t $IMAGE_NAME:$TAG -f $DOCKERFILE .

            # tag with "latest"
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

            # login to DockerHub
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

            # push to DockerHub (both with build number and latest)
            docker push $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest
