apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS imubit_logger;
    USE imubit_logger;
    
    CREATE TABLE logs (
        id MEDIUMINT NOT NULL AUTO_INCREMENT,
        loggerId INT NOT NULL, 
        message VARCHAR(256) NOT NULL,
        dateTimeCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    );
    SET time_zone='+02:00';    
    