apiVersion: v1
kind: Service
metadata:
  name: video-streamer-server
  namespace: default
  labels:
    service: video-streamer-server
spec:
  ports:
  - name: video-streamer-server
    port: 5555
    protocol: TCP
    targetPort: 5555
    nodePort: 30555
  selector:
    service: video-streamer-server
  sessionAffinity: None
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: video-streamer-server
  namespace: default
  labels:
    service: video-streamer-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: video-streamer-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: video-streamer-server
    spec:
      # initContainers:
      # - name: busybox
      #   image: arunvelsriram/utils
      #   command: ["/bin/sh", "-c"]
      #   args: 
      #   - |
      #     curl checkip.amazonaws.com
          
      containers:
      - name: video-streamer-server
        image: yahmlevi/robo-car:video-streamer-server
        # image: yahmlevi/opencv:buildx-1
        imagePullPolicy: Always
        
        # livenessProbe:
        #   exec:
        #     command: 
        #     - "sh"
        #     - "-c"
        #     - ""
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5

        # readinessProbe:
        #   exec:
        #     command: 
        #     - sh 
        #     - -c
        #     - ""
        #   initialDelaySeconds: 30
        #   periodSeconds: 2
        #   timeoutSeconds: 1

        ports:
        - containerPort: 5555
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
